Implement signup page and user verification
tournesol-app/tournesol-frontend pull request #15
Opened 2021-09-12 22:31 UTC by amatissart

One more step to solve https://github.com/tournesol-app/tournesol-meta/issues/96
This PR addresses the 3rd item: "Interface for creating an account & email verification page"

The verification page is very basic . More instructions about how to start and use the platform could be useful.
Its URL is "/verify-user" as defined in the backend configuration:  

https://github.com/tournesol-app/tournesol-backend/blob/1867a6ddf89d433503b4166d98dbda8c189c468f/settings/settings.py#L79

Note that the user needs to login manually after the account has been verified. As far as I can see the "verify-registration" endpoint does not provide the "auto login" feature for our oAuth tokens.

## Screenshots
|Account creation|||
|-|-|-|
|![127 0 0 1_3000_verify-user__user_id=9 timestamp=1631483875](https://user-images.githubusercontent.com/4726554/133004534-b4565b55-5693-4f2f-ba6b-b8f895de5ee0.png)|![127 0 0 1_3000_verify-user__user_id=9 timestamp=163148387](https://user-images.githubusercontent.com/4726554/133004562-442dacc8-e370-4c45-a41f-c16739cd5515.png)|![image](https://user-images.githubusercontent.com/4726554/133004584-162c1ab7-b931-42f3-85e2-af999779ad36.png)

|Verification|
|-|
|<img src="https://user-images.githubusercontent.com/4726554/133004594-dffa5bf8-b279-491c-b5b2-6b29936da025.png" width="250px">

2021-09-15 15:03 UTC, sandre35 requested changes
Excellent job

2021-09-15 15:03 UTC, sandre35 commented on src/pages/signup/Signup.tsx
> +  }
For me, this check should be done in `App.tsx` when you want to access to the page.
If you are already you shouldn't reach this part of the code

2021-09-16 19:21 UTC, amatissart commented on src/pages/signup/Signup.tsx
> +  }
Ok, I made the change.  
It should not make any difference on the behavior, but it may be cleaner indeed.

2021-09-17 08:57 UTC, sandre35 approved these changes

2021-09-17 15:18 UTC, merged