Comparison Interface
tournesol-app/tournesol-frontend pull request #19
Opened 2021-09-16 22:04 UTC by lfaucon

Hey :) 

This PR is not yet perfect, but I would really welcome reviews and suggestions. The code is rather large, that's why it took me so long to get it done. There are multiple bugs here and there. I also find multiple small issues with the backend and automatically generated API, but it should work (hopefully).

2021-09-17 21:39 UTC, sandre35 commented on src/App.tsx
> +          <ComparisonPage />
Since you use useLocation.().search, you don't need to specify videoA or videoB
`<PrivateRoute path="/comparison">
          <ComparisonPage />
</PrivateRoute>`

2021-09-17 22:07 UTC, sandre35 requested changes
Very dense PR indeed ^^
Overall I think it works, but I need to double check because I don't know the behaviour of some functions

2021-09-17 22:07 UTC, sandre35 commented on src/features/comparisons/Comparison.tsx
> +    console.log('slider change', criteria, score);
Need to be removed

2021-09-17 22:07 UTC, sandre35 commented on src/App.tsx
> +          <ComparisonPage />
These repetitions annoys me a bit. 
Using `useParams` specifies clearly which parameters in the url you want.
Maybye using useLocation(), makes this part less repetitive

2021-09-17 22:07 UTC, sandre35 commented on src/utils/video.ts
> +}
Yeah not a big fan of this.
As mentionned in another comment, I don't know if it is very usefull in the current code.

2021-09-20 18:22 UTC, lfaucon commented on src/features/comparisons/Comparison.tsx
> +};
Let's fix this in the second PR getting merged :)

2021-09-20 19:45 UTC, lfaucon commented on src/features/comparisons/Comparison.tsx
> +};
I created the new file on this PR

2021-09-21 08:18 UTC, sandre35 requested changes

2021-09-21 08:18 UTC, sandre35 commented on src/features/comparisons/Comparison.tsx
> +  );
Just a comment : I don't see the utility of `{}` , certainly because I didn't use this function in the past.

2021-09-21 08:20 UTC, sandre35 requested changes
When trying to load random video, you can roll over the same video on position A and B. Comparing the same video doesn't make sens I think. I think this issue need to be fixed.

2021-09-22 18:32 UTC, lfaucon commented on src/features/comparisons/Comparison.tsx
> +  );
It's the initial value required by the reduce method

2021-09-22 18:51 UTC, merged