VideoCard Component creation
tournesol-app/tournesol-frontend pull request #6
Opened 2021-08-12 09:50 UTC by sandre35

Detail of the issue : https://github.com/tournesol-app/tournesol-meta/issues/75

2021-08-20 21:50 UTC, lfaucon requested changes
Thanks for this work @sandre35 

I made a few comments on the code, but I can take care of implementing most of the comments I made if you prefer. Let me know :)

2021-08-20 21:50 UTC, lfaucon commented on src/App.tsx
> +        <Route path="/video">
Probably would do well to have annther URL route here `"/video/{videoId}"`. For the usecase of users sharing a link to the analysis page of a video.

2021-08-20 21:50 UTC, lfaucon commented on src/features/videos/VideoCard.tsx
> +        <iframe width="342.25" height="195" src={video_url}></iframe>
I my current work in progress, I made it such that the video embedding does not need to have a fixed size, which helps a lot adapting to multiple screen sizes. We can possibly improve this later

2021-08-20 21:50 UTC, lfaucon commented on src/features/videos/VideoCard.tsx
> +            <p className={classes.title}>title</p>
I would proposr using more of Material UI as we are using it for styling/small components everywhere else.

Instead of styling a title specifically for the current card, maybe could use the following:

```
<Typography variant="h1" component="h2">
    {title}
</Typography>
```

2021-08-20 21:50 UTC, lfaucon commented on src/features/videos/VideoCard.tsx
> +            <p className={classes.channel}>Science for all</p>
As I recommended during our call, all of these should be props of the current component. 

```
function VideoCardFromMetadata({ title, channel, date }) {
  return (
    <div>
      [...]
      <h1>{title}</h1>
      <p>{channel}</p>
      <p>{date}</p>
    </div>
}
```

Then we could use another component

```
function VideoCard({videoId}) {
  const [metadata, setMetadata] = useState(null)
  
  if (!metadata) {
    setMetadata(fetchMetaDate(videoId))
    return <p>Loading . . .</p>;
  }

  const  { title, channel, date } == metadata
  return (
    <VideoCardFromMetadata
      title={title}
      channel={channel}
      date={date}
    />
}

```

2021-08-20 21:50 UTC, lfaucon commented on src/features/videos/VideoApi.tsx
> +}) => {
Is there not the right API call for this in the automatically generate API?

2021-08-21 09:09 UTC, sandre35 commented on src/features/videos/VideoApi.tsx
> +}) => {
The generated API isn't perfect there are some mistakes here and there to call the back (for instance the url API is not fetched ...)

2021-08-29 20:06 UTC, lfaucon approved these changes

2021-08-29 20:07 UTC, merged