Recommandation Page
tournesol-app/tournesol-frontend pull request #9
Opened 2021-08-31 10:11 UTC by sandre35

Related issue : https://github.com/tournesol-app/tournesol-meta/issues/100

2021-09-01 18:48 UTC, sergia-ch commented on src/App.tsx
> +            <VideoRecommandationCard />
Why are they called recomm**a**ndations? :) Maybe the French way is indeed better :)

2021-09-03 15:52 UTC, lfaucon commented on src/features/comparisons/comparisonsAPI.ts
> +};
I wonder whether this is needed or not. I'm quite sure that the comparison backend API works correctly with the automatically generated code. I'm working on the comparison interface in another PR, so you can leave this as it is right now because I will change it soon in any case.

2021-09-03 16:04 UTC, lfaucon commented on src/features/recommendation/RecommendationFilter.tsx
> +          <FormControlLabel
There are too many code duplication in this file:

It may be useful to use a RadioGroup: https://material-ui.com/components/radio-buttons/#radiogroup or something similar 

And also use somthing like: 

```
dateChoices = ["Any", "Today", ... ]
```
and 
```
{ dateChoices.map(label => <FormControlLabel
            control={
              <Checkbox
                icon={<CheckCircleOutline />}
                checkedIcon={<CheckCircle />}
                checked={state.checked == 'checkedToday'}
                onChange={handleStateChange}
                name="checkedToday"
              />
            }
            label={label}
          />)}
```

2021-09-05 12:55 UTC, sergia-ch commented on src/features/comparisons/comparisonsAPI.ts
> +};
+1, I saved myself so much time by using auto-generated code, especially when things were changing.

- By setting a fixed name in the API definition (in the backend), it would continue working, EVEN after changing the endpoint path
- sometimes it's easy to make mistakes with error handling, I had this even not once and not twice when I check for an error, and it's actually not a full check (such as, I check for 4xx but the error could be also with JSON not complying to the schema etc)
- if authorization changes (we had this in the previous version), it's easier to change it in the auto-generated API rather than in the custom code everywhere
- auto-generated API client provides code completion, which is much easier for development and understanding of the code...

2021-09-05 12:57 UTC, sergia-ch commented on src/features/recommendation/RecommendationFilter.tsx
> +          <FormControlLabel
Maybe it could even be a separate component

2021-09-05 12:58 UTC, sergia-ch commented on src/features/recommendation/VideoRecommendationCard.tsx
> +  console.log(videos);
console statement -- doesn't linter disallow those @lfaucon ?

2021-09-05 12:59 UTC, sergia-ch commented on src/features/videos/VideoApi.tsx
> +      const name = data['name'];
I think it could be done with `const {name, publication_date, ...} = data;` see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2021-09-09 16:59 UTC, sergia-ch commented on src/features/videos/VideoApi.tsx
> +      const { name, publication_date, uploader, views, description } = data;
😍

2021-09-09 17:45 UTC, sergia-ch reviewed
Overall, would be awesome to have screenshots for the new page!

2021-09-09 17:45 UTC, sergia-ch commented on src/features/recommendation/VideoRecommandationFromFilters.tsx
> +    if (videos.count == 0) {
In case if there are no videos returned (empty database, error, etc), it seems to issue requests continuously all the time

2021-09-09 17:45 UTC, sergia-ch commented on src/features/recommendation/VideoRecommandationFromFilters.tsx
> +        if (conversionTime.get(event.target.name)) {
Is there a way to make the condition more explicit? Right now it tries to treat the input as date, and treats it as language if that fails. What if there are more potential choices (such as, number of views of the video)?

2021-09-09 20:14 UTC, lfaucon requested changes
Thanks for working on the recommendation page! It will be super important. I made a lot of comments. I'll let you sort out between what you think should be fixed before merging, what you prefer fixing in a future iteration and what I am wrong about.

Additionally to the comments on the code, I find that the whole page would benefit from having more space rather than a thin column in the center.

![Screenshot 2021-09-09 at 22 10 42](https://user-images.githubusercontent.com/8818081/132755753-a089afaa-c0ce-4b5f-9420-af85d9d32ed8.png)

There are merge conflicts, can you take care of them too?
Thanks

2021-09-09 20:14 UTC, lfaucon commented on src/features/recommendation/VideoRecommendationCard.tsx
> +    marginLeft: '7.78px',
Today I learnt that we css support fractions of pixels. Please, either simplify this or add a comment to explain to other developpers why this value is specfifically chosen

2021-09-09 20:14 UTC, lfaucon commented on src/features/recommendation/VideoRecommendationCard.tsx
> +      </IconButton>
This whole button looks rather weird. 

Can you try with something like this: https://material-ui.com/components/buttons/#buttons-with-icons-and-label

2021-09-09 20:14 UTC, lfaucon commented on src/features/recommendation/VideoRecommendationCard.tsx
> +          <VideoCardFromId videoId={video.video_id} key={video.video_id} />
Using VideoCardFromId here makes the client do additional database request for each video. I believe that the video metadata is included in the return of the API call for recommendations.

See for example here: https://api.staging.tournesol.app/video/

2021-09-09 20:14 UTC, lfaucon commented on src/features/recommendation/VideoRecommendationCard.tsx
> +        props.videos.results.map((video: Video) => (
Would be good to have separated components for the search configuration and the list. Then the recommendation page would look like:

```JavaScript
const REcommendationPage = () => {

    return (<div>
        <SearchFilter />
        <VideoList />
    </div>
```

(of course it will be more complex than this)

2021-09-09 20:14 UTC, lfaucon commented on src/features/videos/VideoApi.tsx
> +      const { name, publication_date, uploader, views, description } = data;
💯

2021-09-09 20:14 UTC, lfaucon commented on src/pages/videos/VideoRecommendation.tsx
> +    marginTop: 120,
The margin at the top is rather weird to me, but maybe it is just my personnal opinion. If you disagree, no need to change it.

2021-09-09 20:14 UTC, lfaucon commented on src/pages/videos/VideoRecommendation.tsx
> +    </div>
Maybe one of the divs here is not necessary (unsure about whether it changes the style)

2021-09-10 11:47 UTC, sandre35 commented on src/features/recommendation/VideoRecommandationFromFilters.tsx
> +        if (conversionTime.get(event.target.name)) {
Yeah the solution is not fully satisfying. I am looking for a better way to send the context back to the parent component

2021-09-10 11:48 UTC, sandre35 commented on src/features/recommendation/VideoRecommandationFromFilters.tsx
> +  });
The issue is that I can't know in advance with function to call in the props onChange

2021-09-10 11:49 UTC, sandre35 commented on src/features/recommendation/RecommendationApi.tsx
> +  })
It depends whether the generated API functions or not. I am going to try using it.

2021-09-10 12:32 UTC, sandre35 commented on src/features/recommendation/RecommendationApi.tsx
> +  })
Okay definitively, the generated API isn't great. It misses on `language` and `publication_date` parameters

2021-09-10 12:48 UTC, amatissart commented on src/features/recommendation/VideoRecommandationFromFilters.tsx
> +  });
It's still possible to define multiple callbacks: `onDateChange`, `onLanguageChange`, etc. 

Another solution could be to handle the update of this object in the child component and simply use a callback to receive the new filter state, possibly encapsulated in a `FilterState` class:
```ts
 onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
 ```
 would become
 ```ts
  onFilterChange: (newFilter: FilterState) => void;
  ```
  Then this parent component would no longer need to handle raw input events.

2021-09-10 12:50 UTC, sandre35 commented on src/features/recommendation/RecommendationApi.tsx
> +  })
Adding these parameters results in no video response because videos don't have yet a attribute `language`

2021-09-10 15:43 UTC, lfaucon commented on src/features/recommendation/VideoRecommendationCard.tsx
> +  console.log(videos);
Not sure, we may want to look into it.

2021-09-10 15:47 UTC, lfaucon commented on src/features/recommendation/RecommendationApi.tsx
> +  })
Yes, you may try adding the parameters by hand on a few videos using the admin interface (should be localhost:8000/admin).

2021-09-10 15:48 UTC, lfaucon commented on src/features/recommendation/RecommendationApi.tsx
> +  })
Indeed, the auto-generated code is incorrect as of now

2021-09-10 16:48 UTC, lfaucon approved these changes

2021-09-10 16:50 UTC, merged